### ISSUE TITLE
Object 'Macrophages' cannot be created

### ISSUE THREAD

**Issue by MingwuDuan** [NUPulmonary/JoshiWatanabe2019#1]
Hi,
When I run the R script file "Joshi_Watanabe_ERJ_2019_asbestos.R", it says

> Error in WhichCells.Seurat(object = x, cells = cells, idents = idents,  : 
  Cannot find the following identities in the object: 6891924

and then object "Macrophages" can not be created.

In fact, in that the idents of "lung" is renamed at line 134, the code at line 151 should be 
> Macrophages <- subset(lung, idents = c('TRAM','IM','MoAM'))

instead of

> Macrophages <- subset(lung, idents = c(6,8,9,19,24))

**Comment by amisharin** [comment]
Thank you, Mingwu, will fix this shortly.
